name: Flux MAUI CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-framework: [net7.0-android, net7.0-windows, net7.0-ios]
    timeout-minutes: 30  # Extend timeout limit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Install workloads
      - name: Install .NET MAUI workloads
        run: dotnet workload install android ios maccatalyst

      # Cache workload installation
      - name: Cache workload installation
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Build for specific platform
      - name: Build for ${{ matrix.target-framework }}
        run: dotnet build --framework ${{ matrix.target-framework }} --configuration Release
