name: Flux MAUI CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [android, windows]
    timeout-minutes: 30  # Extend timeout limit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Install workloads (run separately)
      - name: Install .NET MAUI workloads
        run: dotnet workload restore

      # Cache workload installation
      - name: Cache workload installation
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Build the project for the specific platform
      - name: Build for ${{ matrix.target-platform }}
        run: dotnet build --framework ${{ matrix.target-platform }} --configuration Release
