name: Flux MAUI CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [android, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build for ${{ matrix.target-platform }}
        run: dotnet build --target ${matrix.target-platform} --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build Android APK
        run: dotnet publish MyMauiApp.csproj -f:net7.0-android -c:Release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flux-Android-APK
          path: ./path/to/apk/output

